---
# Reference: https://clouddocs.f5.com/products/orchestration/ansible/devel/f5_bigip/modules_2_0/bigip_sslo_config_utility_module.html#bigip-sslo-config-utility-module-2
#DONE

- name: Perform SSLO Delete All Utility Function
  hosts: all
  gather_facts: False

  collections:
    - f5networks.f5_bigip
  connection: httpapi

  vars:
    # ansible_host: "172.16.1.83"
    ansible_httpapi_port: 443
    ansible_user: "admin"
    ansible_httpapi_password: "admin"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    ## Delete all SSLO Configuration Objects
    - name: Remove entire SSLO config
      bigip_sslo_config_utility:
        utility: delete-all
        timeout: 60
